---
- name: Generic UNIX NTP configuration
  become: True
  notify: restart ntp
  lineinfile:
    path: "{{ ticktockconf }}"
    line: "{{ ticktockpooldirective | default('pool') }} {{ ticktockpool }} iburst"
