---
dependency:
  name: galaxy
driver:
  name: gce
lint:
  name: yamllint
platforms:
  - name: gcp-centos-7
    image: centos-7
  - name: gcp-debian-8
    image: debian-8
  - name: gcp-debian-9
    image: debian-9
  - name: gcp-debian-10
    image: debian-10
  - name: gcp-freebsd-11
    external_projects: freebsd-org-cloud-dev
    image_family: freebsd-11-3-snap
  - name: gcp-freebsd-12
    external_projects: freebsd-org-cloud-dev
    image_family: freebsd-12-0-snap
  - name: gcp-opensuse-leap
    external_projects: opensuse-cloud
    image_family: opensuse-leap
  - name: gcp-rhel-8
    external_projects: rhel-cloud
    image_family: rhel-8
  - name: gcp-sles-15
    external_projects: suse-cloud
    image_family: sles-15
  - name: gcp-ubuntu-18
    external_projects: gce-uefi-images
    image_family: ubuntu-1804-lts
provisioner:
  name: ansible
  log: True
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
