---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Install python for Ansible
      # TODO install python on more platforms
      raw: python -V || python3 -V || (apt -y update && apt install -y python-minimal python-zipstream)
      become: true
      changed_when: false

- name: Prepare - APT
  hosts: ~.*debian.*
  become: True
  tasks:
    # REMOVAL OF JESSIE-UPDATES AND JESSIE-BACKPORTS FROM DEBIAN MIRRORS
    # https://www.lucas-nussbaum.net/blog/?p=947
    - name: Fix archived suites
      block:
        - name: Remove sources
          file:
            name: /etc/apt/sources.list
            state: absent
          loop:
            - /etc/apt/sources.list
            - /etc/apt/sources.list.d/backports.list
        - name: oldoldstable
          copy:
            dest: /etc/apt/sources.list.d/oldoldstable.list
            content: "deb http://deb.debian.org/debian/ {{ansible_distribution_release|lower}} main"
        - name: backports
          copy:
            dest: /etc/apt/sources.list.d/backports.list
            content: "deb http://archive.debian.org/debian/ {{ansible_distribution_release|lower}}-backports main contrib non-free"

        - name: release is expired
          copy:
            dest: /etc/apt/apt.conf.d/99no-check-valid-until
            content: "Acquire::Check-Valid-Until no;"

      when: ansible_distribution == 'Debian' and (ansible_distribution_major_version|int) < 9
